
package com.zjj.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceImpl", targetNamespace = "http://service.zjj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://service.zjj.com/", className = "com.zjj.service.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://service.zjj.com/", className = "com.zjj.service.QueryResponse")
    @Action(input = "http://service.zjj.com/WeatherServiceImpl/queryRequest", output = "http://service.zjj.com/WeatherServiceImpl/queryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orther", targetNamespace = "http://service.zjj.com/", className = "com.zjj.service.Orther")
    @ResponseWrapper(localName = "ortherResponse", targetNamespace = "http://service.zjj.com/", className = "com.zjj.service.OrtherResponse")
    @Action(input = "http://service.zjj.com/WeatherServiceImpl/ortherRequest", output = "http://service.zjj.com/WeatherServiceImpl/ortherResponse")
    public String orther(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
